export const tests = [
  {
    id: 1,
    name: 'Inventario de Depresión de Beck (BDI-2)',
    questions: [
      { question: 'Tristeza', answers: [{ value: 0, option: 'No me siento triste' }, { value: 1, option: 'Me siento triste gran parte del tiempo' }, { value: 2, option: 'Me siento triste todo el tiempo' }, { value: 3, option: 'Me siento tan triste o soy tan infeliz que no puedo soportarlo' }], index: 1 },
      { question: 'Pesimismo', answers: [{ value: 0, option: 'No estoy desalentado respecto del mí futuro' }, { value: 1, option: 'Me siento más desalentado respecto de mi futuro que lo que solía estarlo' }, { value: 2, option: 'No espero que las cosas funcionen para mí' }, { value: 3, option: 'Siento que no hay esperanza para mi futuro y que sólo puede empeorar' }], index: 2 },
      { question: 'Fracaso', answers: [{ value: 0, option: 'No me siento como un fracasado' }, { value: 1, option: 'He fracasado más de lo que hubiera debido' }, { value: 2, option: 'Cuando miro hacia atrás, veo muchos fracasos' }, { value: 3, option: 'Siento que como persona soy un fracaso total' }], index: 3 },
      { question: 'Pérdida de Placer', answers: [{ value: 0, option: 'Obtengo tanto placer como siempre por las cosas de las que disfruto' }, { value: 1, option: 'No disfruto tanto de las cosas como solía hacerlo' }, { value: 2, option: 'Obtengo muy poco placer de las cosas que solía disfrutar' }, { value: 3, option: 'No puedo obtener ningún placer de las cosas de las que solía disfrutar' }], index: 4 },
      { question: 'Sentimientos de Culpa', answers: [{ value: 0, option: 'No me siento particularmente culpable' }, { value: 1, option: 'Me siento culpable respecto de varias cosas que he hecho o que debería haber hecho' }, { value: 2, option: 'Me siento bastante culpable la mayor parte del tiempo' }, { value: 3, option: 'Me siento culpable todo el tiempo' }], index: 5 },
      { question: 'Sentimientos de Castigo', answers: [{ value: 0, option: 'No siento que este siendo castigado' }, { value: 1, option: 'Siento que tal vez pueda ser castigado' }, { value: 2, option: 'Espero ser castigado' }, { value: 3, option: 'Siento que estoy siendo castigado' }], index: 6 },
      { question: 'Disconformidad con uno mismo', answers: [{ value: 0, option: 'Siento acerca de mi lo mismo que siempre' }, { value: 1, option: 'He perdido la confianza en mí mismo' }, { value: 2, option: 'Estoy decepcionado conmigo mismo' }, { value: 3, option: 'No me gusto a mí mismo' }], index: 7 },
      { question: 'Autocrítica', answers: [{ value: 0, option: 'No me critico ni me culpo más de lo habitual' }, { value: 1, option: 'Estoy más crítico conmigo mismo de lo que solía estarlo' }, { value: 2, option: 'Me critico a mí mismo por todos mis errores' }, { value: 3, option: 'Me culpo a mí mismo por todo lo malo que sucede' }], index: 8 },
      { question: 'Pensamientos o Deseos Suicidas', answers: [{ value: 0, option: 'No tengo ningún pensamiento de matarme' }, { value: 1, option: 'He tenido pensamientos de matarme, pero no lo haría' }, { value: 2, option: 'Querría matarme' }, { value: 3, option: 'Me mataría si tuviera la oportunidad de hacerlo' }], index: 9 },
      { question: 'Llanto', answers: [{ value: 0, option: 'No lloro más de lo que solía hacerlo' }, { value: 1, option: 'Lloro más de lo que solía hacerlo' }, { value: 2, option: 'Lloro por cualquier pequeñez' }, { value: 3, option: 'Siento ganas de llorar pero no puedo' }], index: 10 },
      { question: 'Agitación', answers: [{ value: 0, option: 'No estoy más inquieto o tenso que lo habitual' }, { value: 1, option: 'Me siento más inquieto o tenso que lo habitual' }, { value: 2, option: 'Estoy tan inquieto o agitado que me es difícil quedarme quieto' }, { value: 3, option: 'Estoy tan inquieto o agitado que tengo que estar siempre en movimiento o haciendo algo' }], index: 11 },
      { question: 'Pérdida de Interés', answers: [{ value: 0, option: 'No he perdido el interés en otras actividades o personas' }, { value: 1, option: 'Estoy menos interesado que antes en otras personas o cosas' }, { value: 2, option: 'He perdido casi todo el interés en otras personas o cosas' }, { value: 3, option: 'Me es difícil interesarme por algo' }], index: 12 },
      { question: 'Indecisión', answers: [{ value: 0, option: 'Tomo mis propias decisiones tan bien como siempre' }, { value: 1, option: 'Me resulta más difícil que de costumbre tomar decisiones' }, { value: 2, option: 'Encuentro mucha más dificultad que antes para tomar decisiones' }, { value: 3, option: 'Tengo problemas para tomar cualquier decisión' }], index: 13 },
      { question: 'Desvalorización', answers: [{ value: 0, option: 'No siento que yo no sea valioso' }, { value: 1, option: 'No me considero a mi mismo tan valioso y útil como solía considerarme' }, { value: 2, option: 'Me siento menos valioso cuando me comparo con otros' }, { value: 3, option: 'Siento que no valgo nada' }], index: 14 },
      { question: 'Pérdida de Energía', answers: [{ value: 0, option: 'Tengo tanta energía como siempre' }, { value: 1, option: 'Tengo menos energía que la que solía tener' }, { value: 2, option: 'No tengo suficiente energía para hacer demasiado' }, { value: 3, option: 'No tengo energía suficiente para hacer nada' }], index: 15 },
      { question: 'Cambios en los Hábitos de Sueño', answers: [{ value: 0, option: 'No he experimentado ningún cambio en mis hábitos de sueño' }, { value: 1, option: 'Duermo un poco más que lo habitual | Duermo un poco menos que lo habitual' }, { value: 2, option: 'Duermo mucho más que lo habitual | Duermo mucho menos que lo habitual' }, { value: 3, option: 'Duermo la mayor parte del día | Me despierto 1-2 horas más temprano y no puedo volver a dormirme' }], index: 16 },
      { question: 'Irritabilidad', answers: [{ value: 0, option: 'No estoy tan irritable que lo habitual' }, { value: 1, option: 'Estoy más irritable que lo habitual' }, { value: 2, option: 'Estoy mucho más irritable que lo habitual' }, { value: 3, option: 'Estoy irritable todo el tiempo' }], index: 17 },
      { question: 'Cambios en el Apetito', answers: [{ value: 0, option: 'No he experimentado ningún cambio en mi apetito' }, { value: 1, option: 'Mi apetito es un poco menor que lo habitual | Mi apetito es un poco mayor que lo habitual' }, { value: 2, option: 'Mi apetito es mucho menor que antes | Mi apetito es mucho mayor que lo habitual' }, { value: 3, option: 'No tengo apetito en absoluto | Quiero comer todo el día' }], index: 18 },
      { question: 'Dificultad de Concentración', answers: [{ value: 0, option: 'Puedo concentrarme tan bien como siempre' }, { value: 1, option: 'No puedo concentrarme tan bien como habitualmente' }, { value: 2, option: 'Me es difícil mantener la mente en algo por mucho tiempo' }, { value: 3, option: 'Encuentro que no puedo concentrarme en nada' }], index: 19 },
      { question: 'Cansancio o Fatiga', answers: [{ value: 0, option: 'No estoy más cansado o fatigado que lo habitual' }, { value: 1, option: 'Me fatigo o me canso más fácilmente que lo habitual' }, { value: 2, option: 'Estoy demasiado fatigado o cansado para hacer muchas de las cosas que solía hacer' }, { value: 3, option: 'Estoy demasiado fatigado o cansado para hacer la mayoría de las cosas que solía hacer' }], index: 20 },
      { question: 'Pérdida de Interés en el Sexo', answers: [{ value: 0, option: 'No he notado ningún cambio reciente en mi interés por el sexo' }, { value: 1, option: 'Estoy menos interesado en el sexo de lo que solía estarlo' }, { value: 2, option: 'Estoy mucho menos interesado en el sexo' }, { value: 3, option: 'He perdido completamente el interés en el sexo' }], index: 21 }
    ]
  },
  {
    id: 2,
    name: 'Inventario de síntomas SCL-90-R de L. Derogatis'
  },
  {
    id: 3,
    name: 'Escala de ansiedad de Hamilton'
  }
]
